download_server/download_server/urls.py
from django.contrib import admin
from django.urls import path, include
import downloader.urls as downloader

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(downloader, namespace='downloader')),
]

download_server/downloader/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from .views import *
#url for app
app_name = 'downloader'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='index/', permanent = False), name='$'),
    url(r'index/', index, name='index'),
    url(r'progress/', progress, name='progress'),
    url(r'download/', download, name='download'),
]

download_server/downloader/models.py
from django.db import models

# Create your models here.

download_server/downloader/views.py
from background_task import background
from django.http import FileResponse
from django.shortcuts import render

import pika
import wget

# Create your views here.
def index(request):
    response = {}
    return render(request, 'base.html', response)

def progress(request):
    response = {}
    if request.POST:
        file_url = request.POST['url']
        downloadFile(file_url)
    return render(request, 'download_progress.html', response)

def download(request):
    filename = request.GET['filename']
    file = open(filename, 'rb')
    return FileResponse(file)

# code inspired from https://medium.com/@petehouston/download-files-with-progress-in-python-96f14f6417a2 with modification
def bar_custom(current, total, width=80):
    progress_message = "Downloading: %d%% [%d / %d] bytes" % (current / total * 100, current, total)
    sendMessage(progress_message)

@background(schedule=1)
def downloadFile(url):
    filename = wget.download(url, bar=bar_custom)
    sendMessage('Access this url to view file: <a>http://152.118.148.95:20337/download/?filename=' + filename + '</a>')

# from rabbitmq tutorial https://www.rabbitmq.com/tutorials/tutorial-three-python.html
def sendMessage(message):
    routing_key = 'dummyRoutingKey123'
    credentials = pika.PlainCredentials('0806444524', '0806444524')
    connectionParameters = pika.ConnectionParameters('152.118.148.95', 5672, '/0806444524', credentials)
    connection = pika.BlockingConnection(connectionParameters)
    channel = connection.channel()
    channel.exchange_declare(exchange='1606833476', exchange_type='direct')
    channel.queue_declare(queue=routing_key)
    channel.basic_publish(exchange='1606833476', routing_key=routing_key, body=message)
    print(" [x] Sent %r:%r" % (routing_key, message))
    connection.close()

download_server/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#342345">
  <title> {% block title %} LAW File Downloader {% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Raleway:900|Raleway' rel='stylesheet'>
  <meta name="viewport" content="initial-scale=1.0, width=device-width" />
</head>

<body>
  <header>
  </header>
  <content>
    <div class="col-md-10 offset-md-1 mt-5">
    <section name="container" class="content">
    <h2>Download File From URL</h2>
    <form id="form" name="form" method="POST" action="{% url 'downloader:progress' %}" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="text" name="url" placeholder="Insert URL Here">
      <br>
      <button type="submit" class="btn btn-success">Submit</button>
    </form>
    <br>
    </div>
  </content>
  <footer>
  </footer>
</body>

download_server/templates/download_progress.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#342345">
    <title> {% block title %} LAW File Downloader {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Raleway:900|Raleway' rel='stylesheet'>
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
</head>

<body>
    <header>
    </header>
    <content>
        <div class="col-md-10 offset-md-1 mt-5">
            <section name="container" class="content">
                <h1>File Download Progress</h1>
                <br>
                <h3>Status:</h3>
                <br>
                <p id="status">Downloading...</p>
                <br>
        </div>
    </content>
    <footer>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sockjs-client/1.1.4/sockjs.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/stomp.js/2.3.3/stomp.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script type="text/javascript">
        WebSocketImplementation();
        function WebSocketImplementation() {
            if ("WebSocket" in window) {
                var routing_key = 'dummyRoutingKey123';
                var ws_stomp_display = new SockJS('http://152.118.148.95:15674/stomp');
                var client_display = Stomp.over(ws_stomp_display);
                var mq_queue_display = "/exchange/1606833476/" + routing_key;
                var on_connect_display = function () {
                    console.log('connected');
                    client_display.subscribe(mq_queue_display, on_message_display);
                };
                var on_error_display = function () {
                    console.log('error');
                };
                var on_message_display = function (m) {
                    console.log('message received');
                    $('#status').html(m.body);
                };
                client_display.connect('0806444524', '0806444524', on_connect_display, on_error_display, '/0806444524');
            } else {
                alert("WebSocket NOT supported by your Browser!");
            }
        }
    </script>
</body>